### ISSUE TITLE
Crash on iOS caused by DeleteNativeItem method

### ISSUE THREAD

**Issue by Maxikq** [amay077/Xamarin.Forms.GoogleMaps#425]
### SUMMARY

Recently I received on Crashlytics a few crashes from multiple users. I wasn't able to reproduce it. There is possibility, that it may happen while terminating app and is not visible for the user, however it should be investigated.

### VERSIONS

* Xamarin.Forms.GoogleMaps - 2.2.1
* Xamarin.Forms - 2.5.0.91635

### PLATFORMS

- [ ] Android
- [x] iOS
- [ ] UWP

### HOW TO REPRODUCE

I wasn't able to reproduce it, however I received on Crashlytics call stack:
```csharp
Crashed: tid_303

EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000

0  MyApp.iOS        0x1035afacc Xamarin_Forms_GoogleMaps_Logics_iOS_PinLogic_DeleteNativeItem_Xamarin_Forms_GoogleMaps_Pin (<unknown>:1)
1  MyApp.iOS        0x152dae2c0 (Missing)
2  MyApp.iOS        0x10353cfa4 Xamarin_Forms_GoogleMaps_Logics_DefaultLogic_3_TOuter_REF_TNative_REF_TNativeMap_REF_RestoreItems (<unknown>:1)
3  MyApp.iOS        0x1035b352c Xamarin_Forms_GoogleMaps_iOS_MapRenderer_OnElementChanged_Xamarin_Forms_Platform_iOS_ElementChangedEventArgs_1_Xamarin_Forms_View (<unknown>:1)
4  MyApp.iOS        0x102c3d910 Xamarin_Forms_Platform_iOS_VisualElementRenderer_1_TElement_REF_SetElement_TElement_REF (<unknown>:1)
5  MyApp.iOS        0x102c3d1b0 Xamarin_Forms_Platform_iOS_VisualElementRenderer_1_TElement_REF_Xamarin_Forms_Platform_iOS_IVisualElementRenderer_SetElement_Xamarin_Forms_VisualElement (<unknown>:1)
6  MyApp.iOS        0x102c3645c Xamarin_Forms_Platform_iOS_Platform_CreateRenderer_Xamarin_Forms_VisualElement (<unknown>:1)
7  MyApp.iOS        0x102c79128 Xamarin_Forms_Platform_iOS_ViewCellRenderer_ViewTableCell_GetNewRenderer (<unknown>:1)
8  MyApp.iOS        0x102c7937c Xamarin_Forms_Platform_iOS_ViewCellRenderer_ViewTableCell_UpdateCell_Xamarin_Forms_ViewCell (<unknown>:1)
9  MyApp.iOS        0x102c78a10 Xamarin_Forms_Platform_iOS_ViewCellRenderer_ViewTableCell_set_ViewCell_Xamarin_Forms_ViewCell (<unknown>:1)
10 MyApp.iOS        0x102c42fe4 Xamarin_Forms_Platform_iOS_ViewCellRenderer_GetCell_Xamarin_Forms_Cell_UIKit_UITableViewCell_UIKit_UITableView (<unknown>:1)
11 MyApp.iOS        0x10233c40c MyApp_iOS_CustomRenderer_CustomViewCellRenderer_GetCell_Xamarin_Forms_Cell_UIKit_UITableViewCell_UIKit_UITableView (CustomViewCellRenderer.cs:12)
12 MyApp.iOS        0x102c407dc Xamarin_Forms_Platform_iOS_CellTableViewCell_GetNativeCell_UIKit_UITableView_Xamarin_Forms_Cell_bool_string (<unknown>:1)
13 MyApp.iOS        0x102c69cfc Xamarin_Forms_Platform_iOS_TableViewModelRenderer_GetCell_UIKit_UITableView_Foundation_NSIndexPath (<unknown>:1)
14 MyApp.iOS        0x1025e1c44 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 3172032
15 MyApp.iOS        0x103b2cb7c mono_jit_runtime_invoke (mini-runtime.c:2526)
16 MyApp.iOS        0x103ba6230 do_runtime_invoke (object.c:2829)
17 MyApp.iOS        0x103ba6190 mono_runtime_invoke (object.c:2983)
18 MyApp.iOS        0x10230a9a4 native_to_managed_trampoline_38(objc_object*, objc_selector*, _MonoMethod**, UITableView*, NSIndexPath*, unsigned int) (registrar.m:1706)
19 MyApp.iOS        0x10230a7a4 -[Xamarin_Forms_Platform_iOS_TableViewModelRenderer tableView:cellForRowAtIndexPath:] (registrar.m:10784)
20 UIKit                          0x18cba393c -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:] + 664
21 UIKit                          0x18cba3ea0 -[UITableView _createPreparedCellForGlobalRow:willDisplay:] + 80
22 UIKit                          0x18cb839e4 -[UITableView _updateVisibleCellsNow:isRecursive:] + 2140
23 UIKit                          0x18c9394fc -[UITableView layoutSubviews] + 140
24 UIKit                          0x18c8662f8 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1276
25 QuartzCore                     0x18741fec8 -[CALayer layoutSublayers] + 184
26 QuartzCore                     0x187423fa8 CA::Layer::layout_if_needed(CA::Transaction*) + 332
27 QuartzCore                     0x187392a98 CA::Context::commit_transaction(CA::Transaction*) + 336
28 QuartzCore                     0x1873b8eb4 CA::Transaction::commit() + 540
29 QuartzCore                     0x1873b9cf4 CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 92
30 CoreFoundation                 0x1833d9848 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32
31 CoreFoundation                 0x1833d7200 __CFRunLoopDoObservers + 412
32 CoreFoundation                 0x1833d77bc __CFRunLoopRun + 1292
33 CoreFoundation                 0x1832f7fb8 CFRunLoopRunSpecific + 436
34 GraphicsServices               0x18518ff84 GSEventRunModal + 100
35 UIKit                          0x18c8cc2e8 UIApplicationMain + 208
36 MyApp.iOS        0x102d9bbe0 wrapper_managed_to_native_UIKit_UIApplication_UIApplicationMain_int_string___intptr_intptr (<unknown>:1)
37 MyApp.iOS        0x102d268cc UIKit_UIApplication_Main_string___intptr_intptr (UIApplication.cs:79)
38 MyApp.iOS        0x102d2688c UIKit_UIApplication_Main_string___string_string (UIApplication.cs:63)
39 MyApp.iOS        0x1023306f4 MyApp_iOS_Application_Main_string__ (Main.cs:10)
40 MyApp.iOS        0x1025e1c44 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 3172032
41 MyApp.iOS        0x103b2cb7c mono_jit_runtime_invoke (mini-runtime.c:2526)
42 MyApp.iOS        0x103ba6230 do_runtime_invoke (object.c:2829)
43 MyApp.iOS        0x103ba9390 do_exec_main_checked (object.c:2983)
44 MyApp.iOS        0x103b10de0 mono_jit_exec (driver.g.c:1040)
45 MyApp.iOS        0x103c5ce00 xamarin_main (monotouch-main.m:483)
46 MyApp.iOS        0x102330650 main (main.m:163)
47 libdyld.dylib                  0x182e1a56c start + 4
```

**Comment by svilupposoftwarepharmaidea** [comment]
I've had a similar problem.

**VERSIONS**
Xamarin.Forms.GoogleMaps - 2.3.0
Xamarin.Google.iOS.Maps - 2.5.0
Xamarin.Forms - 2.5.0.122203

**PLATFORMS**
 iOS

Call stack:
```
Xamarin_Forms_GoogleMaps_iOS_Xamarin_Forms_GoogleMaps_Logics_iOS_PinLogic_DeleteNativeItem_Xamarin_Forms_GoogleMaps_Pin + 26096784
1  PharmaIdea.Rea.Mobile.iOS      0x103bf655c Xamarin_Forms_GoogleMaps_iOS_Xamarin_Forms_GoogleMaps_Logics_iOS_PinLogic_DeleteNativeItem_Xamarin_Forms_GoogleMaps_Pin + 26096784
2  PharmaIdea.Rea.Mobile.iOS      0x10358c334 Xamarin_Forms_GoogleMaps_Logics_DefaultLogic_3_TOuter_REF_TNative_REF_TNativeMap_REF_RestoreItems (<unknown>:1)
3  PharmaIdea.Rea.Mobile.iOS      0x103bf8bcc Xamarin_Forms_GoogleMaps_iOS_Xamarin_Forms_GoogleMaps_iOS_MapRenderer_OnElementChanged_Xamarin_Forms_Platform_iOS_ElementChangedEventArgs_1_Xamarin_Forms_View + 26106624
4  PharmaIdea.Rea.Mobile.iOS      0x102c351f4 Xamarin_Forms_Platform_iOS_Xamarin_Forms_Platform_iOS_VisualElementRenderer_1_TElement_REF_SetElement_TElement_REF (.D:\agent\_work\1\s\Xamarin.Forms.Platform.iOS\VisualElementRenderer.cs:189)
5  PharmaIdea.Rea.Mobile.iOS      0x102c34d1c Xamarin_Forms_Platform_iOS_Xamarin_Forms_Platform_iOS_VisualElementRenderer_1_TElement_REF_Xamarin_Forms_Platform_iOS_IVisualElementRenderer_SetElement_Xamarin_Forms_VisualElement (.D:\agent\_work\1\s\Xamarin.Forms.Platform.iOS\VisualElementRenderer.cs:141)
6  PharmaIdea.Rea.Mobile.iOS      0x102c3028c Xamarin_Forms_Platform_iOS_Xamarin_Forms_Platform_iOS_Platform_CreateRenderer_Xamarin_Forms_VisualElement (.D:\agent\_work\1\s\Xamarin.Forms.Platform.iOS\Platform.cs:193)
7  PharmaIdea.Rea.Mobile.iOS      0x102c3415c Xamarin_Forms_Platform_iOS_Xamarin_Forms_Platform_iOS_VisualElementPackager_OnChildAdded_Xamarin_Forms_VisualElement (.D:\agent\_work\1\s\Xamarin.Forms.Platform.iOS\VisualElementPackager.cs:77)
8  PharmaIdea.Rea.Mobile.iOS      0x102c33fc0 Xamarin_Forms_Platform_iOS_Xamarin_Forms_Platform_iOS_VisualElementPackager_Load (.D:\agent\_work\1\s\Xamarin.Forms.Platform.iOS\VisualElementPackager.cs:41)
9  PharmaIdea.Rea.Mobile.iOS      0x102c35160 Xamarin_Forms_Platform_iOS_Xamarin_Forms_Platform_iOS_VisualElementRenderer_1_TElement_REF_SetElement_TElement_REF (.D:\agent\_work\1\s\Xamarin.Forms.Platform.iOS\VisualElementRenderer.cs:179)
10 PharmaIdea.Rea.Mobile.iOS      0x102c34d1c Xamarin_Forms_Platform_iOS_Xamarin_Forms_Platform_iOS_VisualElementRenderer_1_TElement_REF_Xamarin_Forms_Platform_iOS_IVisualElementRenderer_SetElement_Xamarin_Forms_VisualElement (.D:\agent\_work\1\s\Xamarin.Forms.Platform.iOS\VisualElementRenderer.cs:141)
11 PharmaIdea.Rea.Mobile.iOS      0x102c3028c Xamarin_Forms_Platform_iOS_Xamarin_Forms_Platform_iOS_Platform_CreateRenderer_Xamarin_Forms_VisualElement (.D:\agent\_work\1\s\Xamarin.Forms.Platform.iOS\Platform.cs:193)
12 PharmaIdea.Rea.Mobile.iOS      0x102c3415c Xamarin_Forms_Platform_iOS_Xamarin_Forms_Platform_iOS_VisualElementPackager_OnChildAdded_Xamarin_Forms_VisualElement (.D:\agent\_work\1\s\Xamarin.Forms.Platform.iOS\VisualElementPackager.cs:77)
13 PharmaIdea.Rea.Mobile.iOS      0x102c344b0 Xamarin_Forms_Platform_iOS_Xamarin_Forms_Platform_iOS_VisualElementPackager_OnChildAdded_object_Xamarin_Forms_ElementEventArgs (.D:\agent\_work\1\s\Xamarin.Forms.Platform.iOS\VisualElementPackager.cs:130)
14 PharmaIdea.Rea.Mobile.iOS      0x10272c488 Xamarin_Forms_Core_Xamarin_Forms_Element_OnChildAdded_Xamarin_Forms_Element (.D:\agent\_work\1\s\Xamarin.Forms.Core\Element.cs:377)
15 PharmaIdea.Rea.Mobile.iOS      0x10273697c Xamarin_Forms_Core_Xamarin_Forms_VisualElement_OnChildAdded_Xamarin_Forms_Element (.D:\agent\_work\1\s\Xamarin.Forms.Core\VisualElement.cs:578)
16 PharmaIdea.Rea.Mobile.iOS      0x1026ec474 Xamarin_Forms_Core_Xamarin_Forms_Page_OnInternalAdded_Xamarin_Forms_VisualElement (.D:\agent\_work\1\s\Xamarin.Forms.Core\Page.cs:356)
17 PharmaIdea.Rea.Mobile.iOS      0x1026ec3a8 Xamarin_Forms_Core_Xamarin_Forms_Page_InternalChildrenOnCollectionChanged_object_System_Collections_Specialized_NotifyCollectionChangedEventArgs (.D:\agent\_work\1\s\Xamarin.Forms.Core\Page.cs:347)
18 PharmaIdea.Rea.Mobile.iOS      0x1029e2088 System_System_Collections_ObjectModel_ObservableCollection_1_T_REF_OnCollectionChanged_System_Collections_Specialized_NotifyCollectionChangedEventArgs (observablecollection.cs:288)
19 PharmaIdea.Rea.Mobile.iOS      0x1029e2280 System_System_Collections_ObjectModel_ObservableCollection_1_T_REF_OnCollectionChanged_System_Collections_Specialized_NotifyCollectionChangedAction_object_int (observablecollection.cs:352)
20 PharmaIdea.Rea.Mobile.iOS      0x1029e1d0c System_System_Collections_ObjectModel_ObservableCollection_1_T_REF_InsertItem_int_T_REF (observablecollection.cs:220)
21 PharmaIdea.Rea.Mobile.iOS      0x1025a0d9c mscorlib_System_Collections_ObjectModel_Collection_1_T_REF_Add_T_REF (collection.cs:68)
22 PharmaIdea.Rea.Mobile.iOS      0x1026e3158 Xamarin_Forms_Core_Xamarin_Forms_TemplateUtilities_OnContentChanged_Xamarin_Forms_BindableObject_object_object (.D:\agent\_work\1\s\Xamarin.Forms.Core\TemplateUtilities.cs:76)
23 PharmaIdea.Rea.Mobile.iOS      0x1026d8624 Xamarin_Forms_Core_Xamarin_Forms_BindableObject_SetValueActual_Xamarin_Forms_BindableProperty_Xamarin_Forms_BindableObject_BindablePropertyContext_object_bool_Xamarin_Forms_Internals_SetValueFlags_bool (.D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:599)
24 PharmaIdea.Rea.Mobile.iOS      0x1026d7a50 Xamarin_Forms_Core_Xamarin_Forms_BindableObject_SetValueCore_Xamarin_Forms_BindableProperty_object_Xamarin_Forms_Internals_SetValueFlags_Xamarin_Forms_BindableObject_SetValuePrivateFlags (.D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:393)
25 PharmaIdea.Rea.Mobile.iOS      0x1026d8344 Xamarin_Forms_Core_Xamarin_Forms_BindableObject_SetValue_Xamarin_Forms_BindableProperty_object_bool_bool (.D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:546)
26 PharmaIdea.Rea.Mobile.iOS      0x102731c48 Xamarin_Forms_Core_Xamarin_Forms_ContentPage_set_Content_Xamarin_Forms_View (.D:\agent\_work\1\s\Xamarin.Forms.Core\ContentPage.cs:11)
27 PharmaIdea.Rea.Mobile.iOS      0x102f039a8 PharmaIdea_Rea_Mobile_Pages_Customers_CustomerMapPage__MakeMapd__6_MoveNext (C:\dparisi\Progetti\PharmaIdeaReapp\Development\PharmaIdea.Rea.Mobile\Pages\Customers\CustomerMapPage.cs:163)
28 PharmaIdea.Rea.Mobile.iOS      0x1030a1a48 PharmaIdea_Rea_Mobile_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_Start_PharmaIdea_Rea_Mobile_Pages_Customers_CustomerMapPage__MakeMapd__6_PharmaIdea_Rea_Mobile_Pages_Customers_CustomerMapPage__MakeMapd__6_ (AsyncMethodBuilder.cs:316)
29 PharmaIdea.Rea.Mobile.iOS      0x10303a194 PharmaIdea_Rea_Mobile_PharmaIdea_Rea_Mobile_Pages_Customers_CustomerMapPage_MakeMap + 13791432
30 PharmaIdea.Rea.Mobile.iOS      0x102f03ad4 PharmaIdea_Rea_Mobile_Pages_Customers_CustomerMapPage__OnAppearingd__7_MoveNext (C:\dparisi\Progetti\PharmaIdeaReapp\Development\PharmaIdea.Rea.Mobile\Pages\Customers\CustomerMapPage.cs:178)
31 PharmaIdea.Rea.Mobile.iOS      0x1023ec194 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 889032
32 PharmaIdea.Rea.Mobile.iOS      0x104106168 mono_jit_runtime_invoke (mini-runtime.c:2768)
33 PharmaIdea.Rea.Mobile.iOS      0x104181860 do_runtime_invoke (object.c:2862)
34 PharmaIdea.Rea.Mobile.iOS      0x1040eeb38 mono_gsharedvt_constrained_call (jit-icalls.c:1413)
35 PharmaIdea.Rea.Mobile.iOS      0x1023ee680 wrapper_managed_to_native_object___icall_wrapper_mono_gsharedvt_constrained_call_intptr_intptr_intptr_intptr_intptr + 898484
36 PharmaIdea.Rea.Mobile.iOS      0x1023b8254 System_Runtime_CompilerServices_AsyncVoidMethodBuilder_Start_TStateMachine_GSHAREDVT_TStateMachine_GSHAREDVT_ + 676232
37 PharmaIdea.Rea.Mobile.iOS      0x102f02b34 PharmaIdea_Rea_Mobile_Pages_Customers_CustomerMapPage_OnAppearing (<unknown>:1)
38 PharmaIdea.Rea.Mobile.iOS      0x1026ec118 Xamarin_Forms_Core_Xamarin_Forms_Page_SendAppearing (.D:\agent\_work\1\s\Xamarin.Forms.Core\Page.cs:308)
39 PharmaIdea.Rea.Mobile.iOS      0x102c49dd4 Xamarin_Forms_Platform_iOS_Xamarin_Forms_Platform_iOS_PageRenderer_ViewDidAppear_bool (.D:\agent\_work\1\s\Xamarin.Forms.Platform.iOS\Renderers\PageRenderer.cs:94)
40 PharmaIdea.Rea.Mobile.iOS      0x1023ec194 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 889032
41 PharmaIdea.Rea.Mobile.iOS      0x104106168 mono_jit_runtime_invoke (mini-runtime.c:2768)
42 PharmaIdea.Rea.Mobile.iOS      0x104181860 do_runtime_invoke (object.c:2862)
43 PharmaIdea.Rea.Mobile.iOS      0x1041817c0 mono_runtime_invoke (object.c:3016)
44 PharmaIdea.Rea.Mobile.iOS      0x10233e7f8 native_to_managed_trampoline_26(objc_object*, objc_selector*, _MonoMethod**, bool, unsigned int) (registrar.m:1122)
45 PharmaIdea.Rea.Mobile.iOS      0x102346454 -[Xamarin_Forms_Platform_iOS_PageRenderer viewDidAppear:] (registrar.m:11874)
46 UIKit                          0x18ae3a588 -[UIViewController _setViewAppearState:isAnimating:] + 852
47 UIKit                          0x18aec4ca8 __52-[UIViewController _setViewAppearState:isAnimating:]_block_invoke + 264
48 CoreFoundation                 0x181800484 -[__NSSingleObjectArrayI enumerateObjectsWithOptions:usingBlock:] + 76
49 UIKit                          0x18ae3a734 -[UIViewController _setViewAppearState:isAnimating:] + 1280
50 UIKit                          0x18ae3aaf4 -[UIViewController _endAppearanceTransition:] + 228
51 UIKit                          0x18aedfdbc -[UINavigationController navigationTransitionView:didEndTransition:fromView:toView:] + 1328
52 UIKit                          0x18afa681c __49-[UINavigationController _startCustomTransition:]_block_invoke + 252
53 UIKit                          0x18af3287c -[_UIViewControllerTransitionContext completeTransition:] + 116
54 UIKit                          0x18b076c04 __53-[_UINavigationParallaxTransition animateTransition:]_block_invoke.124 + 752
55 UIKit                          0x18ae5a188 -[UIViewAnimationBlockDelegate _didEndBlockAnimation:finished:context:] + 764
56 UIKit                          0x18ae59afc -[UIViewAnimationState sendDelegateAnimationDidStop:finished:] + 312
57 UIKit                          0x18ae59808 -[UIViewAnimationState animationDidStop:finished:] + 296
58 UIKit                          0x18ae598a8 -[UIViewAnimationState animationDidStop:finished:] + 456
59 QuartzCore                     0x1858badc4 CA::Layer::run_animation_callbacks(void*) + 284
60 libdispatch.dylib              0x1811e6a14 _dispatch_client_callout + 16
61 libdispatch.dylib              0x1811f3698 _dispatch_main_queue_callback_4CF$VARIANT$mp + 1016
62 CoreFoundation                 0x18180f344 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
63 CoreFoundation                 0x18180cf20 __CFRunLoopRun + 2012
64 CoreFoundation                 0x18172cc58 CFRunLoopRunSpecific + 436
65 GraphicsServices               0x1835d8f84 GSEventRunModal + 100
66 UIKit                          0x18ae855c4 UIApplicationMain + 236
67 PharmaIdea.Rea.Mobile.iOS      0x102cb5950 wrapper_managed_to_native_UIKit_UIApplication_UIApplicationMain_int_string___intptr_intptr (<unknown>:1)
68 PharmaIdea.Rea.Mobile.iOS      0x102d0e210 Xamarin_iOS_UIKit_UIApplication_Main_string___string_string (UIApplication.cs:63)
69 PharmaIdea.Rea.Mobile.iOS      0x102367cb8 PharmaIdea_Rea_Mobile_iOS_PharmaIdea_Rea_Mobile_iOS_Application_Main_string__ + 347116
70 PharmaIdea.Rea.Mobile.iOS      0x1023ec194 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 889032
71 PharmaIdea.Rea.Mobile.iOS      0x104106168 mono_jit_runtime_invoke (mini-runtime.c:2768)
72 PharmaIdea.Rea.Mobile.iOS      0x104181860 do_runtime_invoke (object.c:2862)
73 PharmaIdea.Rea.Mobile.iOS      0x104184b04 do_exec_main_checked (object.c:3016)
74 PharmaIdea.Rea.Mobile.iOS      0x1040e9650 mono_jit_exec (driver.g.c:1036)
75 PharmaIdea.Rea.Mobile.iOS      0x10423b2e4 xamarin_main (monotouch-main.m:483)
76 PharmaIdea.Rea.Mobile.iOS      0x1023656e8 main (main.m:209)
77 libdyld.dylib                  0x18124c56c start + 4
```

**Comment by amay077** [comment]
We have not received the requested information. 
If you are still experiencing this issue please provide all the requested information and re-open the issue report. 
Thanks!

**Comment by chrisfoulds** [comment]
I am getting the exact same crash and zero idea on how to reproduce, any one resolve this ?

**Comment by chrisfoulds** [comment]
@amay077 beyond stack traces what do you need ?

**Comment by wojciech-kulik** [comment]
@chrisfoulds I managed to fix this bug on my own by including source code and editing file:
`Xamarin.Forms.GoogleMaps-2.2.1/Xamarin.Forms.GoogleMaps/Xamarin.Forms.GoogleMaps.iOS/Logics/PinLogic.cs`

Here is my fix:
![fix](https://i.imgur.com/5lzDzbu.png)

**Comment by chrisfoulds** [comment]
Many thanks, will do the same. It's always a shame when I have to pull the source code in manually

**Comment by wojciech-kulik** [comment]
@chrisfoulds maybe check first if it's already fixed in the latest version.

**Comment by chrisfoulds** [comment]
@wojciech-kulik I am running latest and xf 3.4 , it's the only main crash I have in the field. Will just add some extra levels of protection

**Comment by PBosnjak** [comment]
Is anyone else still experiencing this issue on version 3.2.1.?
