### ISSUE TITLE
out of memory when use repeatedly Navigation.PushAsync 

### ISSUE THREAD

**Issue by josco007** [amay077/Xamarin.Forms.GoogleMaps#466]
When using a Navigation.PushAsync with a ContentPage that contains a map on Android and a button to navigate to a new page (of the same layout), navigating back and forth repeatedly will eventually cause an out of memory error.

### VERSIONS

* Xamarin.Forms.GoogleMaps - 2.3.0
* Xamarin.Forms - 2.5.0.122203
* 

### PLATFORMS

- [x] Android
- [] iOS
- [ ] UWP

### HOW TO REPRODUCE

1. create a page1 with a button
2.  create page 2 with a map
3. navigate to page2 from page1 using Navigation.PushAsync (new page2()); in button click method
4. go back to page1 using the navigation bar back button.
5.- do step 3 until out of memory occurs

**Comment by josco007** [comment]
I have fixed the bug in this way:

1. I Create a  folder named Custom in xamarin forms project and inside this class:

```
using Xamarin.Forms.GoogleMaps;
namespace MyApp.Custom
{
    public class CustomGoogleMap:Map
    {

    }
}
```

2. In android project I added a folder named Renders and inside this class:

```
using Android.Gms.Maps;
using MyApp.Custom;
using MyApp.Droid.Renders;
using Xamarin.Forms;
using Xamarin.Forms.GoogleMaps.Android;
[assembly: ExportRenderer(typeof(CustomGoogleMap), typeof(GoogleMapRenderer))]
namespace MyApp.Droid.Renders
{
    public class GoogleMapRenderer : MapRenderer
    {
        protected override void Dispose(bool disposing)
        {
            //base.Dispose(disposing);
            (this.Control as MapView).OnPause();
            (this.Control as MapView).OnDestroy();
            (this.Control as MapView).Dispose();
        }
    }
}
```

3.- Then in my map xaml content page:

`<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:MyApp.MarkupExtensions"
             xmlns:maps="clr-namespace:MyApp.Custom"
             x:Class="MyApp.Pages.MapPage">
    <ContentPage.Content>
        <StackLayout>
            <maps:CustomGoogleMap  x:Name="map"
                      InitialCameraUpdate="19.397157, -99.139501, 13, 0, 0"
                      VerticalOptions="FillAndExpand" />
        </StackLayout>
    </ContentPage.Content>
</ContentPage>`

Notice that instead use :
`xmlns:maps="clr-namespace:Xamarin.Forms.GoogleMaps;assembly=Xamarin.Forms.GoogleMaps"` 
I use:
`xmlns:maps="clr-namespace:MyApp.Custom" `


References:
https://bugzilla.xamarin.com/show_bug.cgi?id=39489

https://forums.xamarin.com/discussion/65294/memory-leak-in-the-xamarin-forms-maps-component-on-ios
comment wrote it by JGoldberger

**Comment by cbagpipe** [comment]
Same problem. Official xamarin maps docs says that:

>**MapView** - The MapView is a specialized View subclass which can act as a host for a GoogleMap object.  :exclamation: Users of this class must forward all of the Activity lifecycle methods to the MapView class  :exclamation: .

[https://docs.microsoft.com/en-us/xamarin/android/platform/maps-and-location/maps/maps-api#the-googlemap-class](https://docs.microsoft.com/en-us/xamarin/android/platform/maps-and-location/maps/maps-api#the-googlemap-class)

**Comment by sphairo** [comment]
A caso estas loco @_@ @josco007

**Comment by amay077** [comment]
Fixed at https://github.com/amay077/Xamarin.Forms.GoogleMaps/releases/tag/v3.0.1

**Comment by MaxFe** [comment]
Still have this problem with version 3.1.0.583944. I don't use maps. Only ListViews and other simple Controls.

**Comment by amay077** [comment]
Hi @MaxFe ,

I think it is not Xamarin.Forms.GoogleMaps's bug.

**Comment by ennydz** [comment]
Still have this problem with version 3.3.0
please , anyone have a solution , i lost one week of trying to fix that
