### ISSUE TITLE
The type or namespace name '"cachingnativebitmapdescriptorfactory"' could not be found 

### ISSUE THREAD

**Issue by BillyMartin1964** [amay077/Xamarin.Forms.GoogleMaps#516]
I've tried both the 2.3.0 stable version and the 3.0.0-beta 6 version and they both give me this error in the Android MainActivity.cs of my Xamarin Forms

The type or namespace name '"cachingnativebitmapdescriptorfactory"' could not be found (are you missing a using directive or an assembly reference?

Here's the code:

```
using System;
using AndroidBitmapDescriptor = Android.Gms.Maps.Model.BitmapDescriptor;
using Android.App;
using Android.Content.PM;
using Android.Gms.Maps.Model;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using Android.OS;
using Java.Lang;
using Xamarin.Forms.GoogleMaps.Android;

namespace FishingFanatic.Droid
{
    [Activity(Label = "FishingFanatic", Icon = "@mipmap/icon", Theme = "@style/MainTheme", MainLauncher = true, ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation)]
    public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity
    {
        protected override void OnCreate(Bundle bundle)
        {
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;

            base.OnCreate(bundle);

            global::Xamarin.Forms.Forms.Init(this, bundle);


           // Override default BitmapDescriptorFactory by your implementation. 
            var platformConfig = new PlatformConfig
            {
                BitmapDescriptorFactory = new CachingNativeBitmapDescriptorFactory()
            };

            Xamarin.FormsGoogleMaps.Init(this, bundle, platformConfig); // initialize for Xamarin.Forms.GoogleMaps


            LoadApplication(new App());
        }
    }
}


```

**Comment by amay077** [comment]
I forgot to add ``CachingNativeBitmapDescriptorFactory.cs`` to ``XFGoogleMapSample.Droid.csproj`` (also iOS side).

I fixed it in [sample here](https://github.com/amay077/Xamarin.Forms.GoogleMaps/commit/9d8b27244dd7716b3f9572cb77290283cdbc1bb8).

Please pull again.

**Comment by BillyMartin1964** [comment]
Great. Now is that an update I can do through Nuget, or do I need to add the code to those two files manually?

**Comment by BillyMartin1964** [comment]
@amay077 I don't know what I'm supposed to do to make it work. Do I add the code somewhere or has it been updated on your end? I don't see an update in Nuget and the plugin still shows the same error.
